project_id = "epypncqtkpytsbllicqc"

[functions.calculate-recipe-pricing]
verify_jwt = false

[functions.calculate-business-metrics]
verify_jwt = false

[functions.calculate-ifood-fees]
verify_jwt = false

[functions.generate-combo]
verify_jwt = false

[functions.backup-restore]
verify_jwt = false
